---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: bosh-azure
run:
  path: bosh-azure/ci/tasks/init/init-azure-resources.sh
params:
  azure_bosh_terraform_template:
  azure_subscription_id:
  azure_tenant_id:
  azure_service_principal_id:
  azure_service_principal_password:
  azure_region:
  azure_terraform_prefix:
  azure_terraform_vnet_cidr:
  azure_terraform_subnet_bosh_cidr:
  bosh_domain:
  jumpbox_private_ip:
  jumpbox_hostname:
  vm_admin_username:
  vm_admin_password:
