---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: bosh-azure
run:
  path: bosh-azure/ci/tasks/init/wipe-env.sh
params:
  arg_wipe:
  azure_bosh_terraform_template:
  azure_subscription_id:
  azure_tenant_id:
  azure_service_principal_id:
  azure_service_principal_password:
  azure_region:
  azure_terraform_prefix:
