resources:

- name: bosh-azure
  type: git
  source:
    uri: https://github.com/ntdt/bosh-azure.git
    branch: master

jobs:

- name: init-env
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
    - aggregate:
      - get: bosh-azure
        trigger: false

    - task: wipe-env
      file: bosh-azure/ci/tasks/wipe-env.yml
      params:
          arg_wipe: {{arg_wipe}}
          azure_bosh_terraform_template: {{azure_bosh_terraform_template}}
          azure_subscription_id: {{azure_subscription_id}}
          azure_tenant_id: {{azure_tenant_id}}
          azure_service_principal_id: {{azure_service_principal_id}}
          azure_service_principal_password: {{azure_service_principal_password}}
          azure_region: {{azure_region}}
          azure_terraform_prefix: {{azure_terraform_prefix}}

    - task: init-azure-resources
      file: bosh-azure/ci/tasks/init-azure-resources.yml
      params:
          azure_bosh_terraform_template: {{azure_bosh_terraform_template}}
          azure_subscription_id: {{azure_subscription_id}}
          azure_tenant_id: {{azure_tenant_id}}
          azure_service_principal_id: {{azure_service_principal_id}}
          azure_service_principal_password: {{azure_service_principal_password}}
          azure_region: {{azure_region}}
          azure_terraform_prefix: {{azure_terraform_prefix}}
          azure_terraform_vnet_cidr: {{azure_terraform_vnet_cidr}}
          azure_terraform_subnet_bosh_cidr: {{azure_terraform_subnet_bosh_cidr}}
          bosh_domain: {{bosh_domain}}
          vm_admin_username: {{azure_vm_admin}}
          vm_admin_password: {{azure_vm_password}}
          jumpbox_private_ip: {{jumpbox_private_ip}}
          jumpbox_hostname: {{jumpbox_hostname}}
########################
## bootstrap boot ######
########################
- name: bootstrap-bosh
  serial: true
  max_in_flights: 1
  serial_groups: [full]
  plan:
    - aggregate:
        - get: bosh-azure
          trigger: false
          passed: [ init-env ]
    - task: prepare-bosh-manifest
      file: bosh-azure/ci/tasks/prepare-bosh-manifest.yml
      params:
        bosh_hostname: {{bosh_hostname}}
        bosh_account: {{bosh_account}}
        bosh_account_password: {{bosh_account_password}}
        bosh_public_ip: {{bosh_public_ip}}
        nats_password: {{nats_password}}
        postgres_password: {{postgres_password}}
        registry_password: {{registry_password}}
        blobstore_director_password: {{blobstore_director_password}}
        blobstore_agent_password: {{blobstore_agent_password}}
        hm_password: {{hm_password}}
        
    - task: init-bosh
      file: bosh-azure/ci/tasks/init-bosh.yml
      params:
        abc: abc

