resources:

- name: bosh-azure
  type: git
  source:
    uri: https://github.com/ntdt/bosh-azure.git
    branch: master

jobs:

- name: init-env
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
    - aggregate:
      - get: bosh-azure
        trigger: false

    - task: wipe-env
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/c0-worker
        inputs:
          - name: bosh-azure
        run:
          path: bosh-azure/ci/tasks/init/wipe-env.sh
          params:
            arg_wipe: {{arg_wipe}}
            azure_bosh_terraform_template: {{azure_bosh_terraform_template}}
            azure_subscription_id: {{azure_subscription_id}}
            azure_tenant_id: {{azure_tenant_id}}
            azure_service_principal_id: {{azure_service_principal_id}}
            azure_service_principal_password: {{azure_service_principal_password}}
            azure_region: {{azure_region}}
            azure_terraform_prefix: {{azure_terraform_prefix}}

    - task: init-azure-resources
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: virtmerlin/c0-worker
        inputs:
          - name: bosh-azure
        run:
          path: bosh-azure/ci/tasks/init/init-azure-resources.sh
        params:
          arg_wipe: {{arg_wipe}}
          azure_bosh_terraform_template: {{azure_bosh_terraform_template}}
          azure_subscription_id: {{azure_subscription_id}}
          azure_tenant_id: {{azure_tenant_id}}
          azure_service_principal_id: {{azure_service_principal_id}}
          azure_service_principal_password: {{azure_service_principal_password}}
          azure_region: {{azure_region}}
          azure_terraform_prefix: {{azure_terraform_prefix}}
          azure_terraform_vnet_cidr: {{azure_terraform_vnet_cidr}}
          azure_terraform_subnet_bosh_cidr: {{azure_terraform_subnet_bosh_cidr}}
          bosh_domain: {{bosh_domain}}
